# Generated by Django 4.0.1 on 2022-02-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hardware_reports',
            fields=[
                ('Lab_num', models.CharField(choices=[('LABORATORY 1', 'LABORATORY 1'), ('LABORATORY 2', 'LABORATORY 2'), ('LABORATORY 3', 'LABORATORY 3'), ('LABORATORY 4', 'LABORATORY 4')], max_length=50)),
                ('Pc_num', models.IntegerField(primary_key=True, serialize=False)),
                ('System_unit', models.BooleanField()),
                ('Mouse', models.BooleanField()),
                ('Avr', models.BooleanField()),
                ('Monitor', models.BooleanField()),
                ('Comments', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('Section_name', models.CharField(max_length=50)),
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('Time_in', models.TimeField()),
                ('Time_out', models.TimeField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('User_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password_data', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('Email_data', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=50)),
                ('Password_input', models.CharField(default='', max_length=40)),
                ('Job_description', models.BooleanField()),
                ('Contact_num', models.DecimalField(decimal_places=0, default='', max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='software_reports',
            fields=[
                ('User_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Type_concern', models.CharField(choices=[('Request', 'Request'), ('Complain', 'Complain'), ('Suggest', 'Suggest'), ('Others', 'Others')], max_length=50)),
                ('Lab_num', models.CharField(choices=[('LABORATORY 1', 'LABORATORY 1'), ('LABORATORY 2', 'LABORATORY 2'), ('LABORATORY 3', 'LABORATORY 3'), ('LABORATORY 4', 'LABORATORY 4')], max_length=50)),
                ('Pc_num', models.IntegerField()),
                ('Message', models.CharField(max_length=256)),
            ],
        ),
    ]
