# Generated by Django 4.0.1 on 2022-02-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='index',
            table='i1',
        ),
    ]
